# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Check out code
      uses: actions/checkout@v2

    # Step 2: Set up AWS credentials using secrets stored in GitHub
    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Replace with your AWS region

    # Step 3: Connect to EC2 instance via SSH and copy code
    - name: Copy code to EC2 instance
      env:
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Write the SSH private key to a temporary file
        echo "$SSH_KEY" > private_key.pem
        chmod 600 private_key.pem

        # Copy code to EC2 instance
        scp -i private_key.pem -o "StrictHostKeyChecking=no" -r $GITHUB_WORKSPACE/* ec2-user@${EC2_PUBLIC_IP}:/home/ec2-user/app

        # Clean up
        rm private_key.pem
