# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Check out code
      uses: actions/checkout@v2

    # Step 2: Set up AWS credentials using secrets stored in GitHub
    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Replace with your AWS region

    # Step 3: Connect to EC2 instance via SSH and copy code
    - name: Build & Deploy code on Ec2
      env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.EC2_PUBLIC_IP}}
          USER_NAME: ${{secrets.USER_NAME}}
      
      run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${EC2_PUBLIC_IP}

          # Now we have got the access of EC2 and we will start the deploy .
          cd /home/ubuntu/ &&
          sudo ls
